INSERT INTO privilegios (privilegios) VALUES ("CLIENTE");
INSERT INTO privilegios (privilegios) VALUES ("ADMIN");

INSERT INTO categorias (nombre, descripcion) VALUES ("Vestido","vestidos de diferentes estilos");
INSERT INTO categorias (nombre, descripcion) VALUES ("Short", "shorts de diferentes estilos");
INSERT INTO categorias (nombre, descripcion) VALUES ("Falda", "faldas de diferentes estilos ");
INSERT INTO categorias (nombre, descripcion) VALUES ("Blusa", "blusas de diferentes estilos ");
INSERT INTO categorias (nombre, descripcion) VALUES ("Camisa", "camisas de diferentes estilos");

INSERT INTO clientes (active, privilegio_id_privilegios, telefono, apellido, contraseña, correo, nombre) VALUES (1, 2,  "5646813295", "Salazar", "mango6", "miguel@salazar.com", "Miguel");
INSERT INTO clientes (active, privilegio_id_privilegios, telefono, apellido, contraseña, correo, nombre) VALUES (0, 1,  "8161684558", "Gonzalez", "mango2", "luis@gonzlez.com", "Luis");
INSERT INTO clientes (active, privilegio_id_privilegios, telefono, apellido, contraseña, correo, nombre) VALUES (1, 2,  "5154572854", "Perez", "mango5", "ximena@perez.com", "Ximena");
INSERT INTO clientes (active, privilegio_id_privilegios, telefono, apellido, contraseña, correo, nombre) VALUES (0, 1,  "2584117754", "Rodriguez", "mango8", "michel@rodriguez.com", "Michel");
INSERT INTO clientes (active, privilegio_id_privilegios, telefono, apellido, contraseña, correo, nombre) VALUES (1, 2,  "5416546466", "Mangel", "mango4", "joel@mangel.com", "Joel");
INSERT INTO clientes (active, privilegio_id_privilegios, telefono, apellido, contraseña, correo, nombre) VALUES (1, 2, "732-254-1589", "Martinez", "Am7#hT51", "ana.martinez@gmail.com", "Ana");
INSERT INTO clientes (active, privilegio_id_privilegios, telefono, apellido, contraseña, correo, nombre) VALUES (1, 2, "318-654-2958", "Jimenez", "Cj1#eR62", "carlos.jimenez@gmail.com", "Carlos");
INSERT INTO clientes (active, privilegio_id_privilegios, telefono, apellido, contraseña, correo, nombre) VALUES (1, 2, "402-659-3951", "Vega", "Iv9#sX47", "isabel.vega@gmail.com", "Isabel");
INSERT INTO clientes (active, privilegio_id_privilegios, telefono, apellido, contraseña, correo, nombre) VALUES (1, 2, "619-501-6548", "Dominguez", "Rd3#nY84", "raul.dominguez@gmail.com", "Raúl");
INSERT INTO clientes (active, privilegio_id_privilegios, telefono, apellido, contraseña, correo, nombre) VALUES (1, 2, "505-711-3854", "Nieto", "En10#zM95", "elena.nieto@gmail.com", "Elena");



INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (550.00, 1, "S", "Algodón", "Pecho: 38 cm Cintura: 32 cm Largo: 86 cm", "Usado Alice&Olivia Detalles: Ninguno", "https://i.pinimg.com/originals/d0/32/53/d032539e7b06eab008e8b7b8a8073577.jpg", "Vestido sin mangas rosa con negro Alice+Olivia");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (450.0, 1, "S", "Poliester", "Pecho : 38 cm Cintura : 32 cm Largo: 60 cm", "Nuevo Zara Detalles: Ninguno", "https://i.pinimg.com/originals/26/9b/e8/269be8210b4f3c062b400e3b029fbba2.jpg", "Vestido Strapless Zara");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (550.0, 1, "S", "Algodón", "Pecho : 38 cm Cintura : 32 cm Largo: 86 cm", "Usado Alice&Olivia Detalles: Ninguno", "https://i.pinimg.com/originals/d0/32/53/d032539e7b06eab008e8b7b8a8073577.jpg", "Vestido Sin Mangas Rosa Con Negro Alice+Olivia");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (350.0, 1, "S", "Algodón", "Pecho : 33cm Cintura : 31 cm Largo:  82 cm", "Usado Ninguno Marca:DEE ELLE Detalles: Ninguno", "https://i.pinimg.com/originals/4d/7f/d9/4d7fd9397c38722de3578916d2de90a6.jpg", "Vestido Sin Mangas Dee Elle")
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (360.0, 1, "XS", "Poliester", "Pecho : 27 cm Cintura : 26 cm Largo: 71 cm", "Seminuevo Princess Polly Detalles: Ninguno", "https://i.pinimg.com/originals/72/15/48/721548d2a9590c76e7c51bd2d1057f6b.jpg", "Vestido Al Hombro Con Flores Marca Princess Polly");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (450.0, 1, "XS", "nylon", "Pecho : 39 cm Cintura : 39 cm Largo: 89 cm", "Usado ABS Detalles: Ninguno", "https://i.pinimg.com/originals/75/e0/08/75e008e3c34555e568828cad06412094.jpg", "Vestido Negro Con Maya  Marca Abs");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (550.0, 1, "XS", "nylon", "Pecho : 38 cm Cintura : 32 cm Largo: 66 cm", "Usado Alice&Olivia Detalles: Ninguno", "https://i.pinimg.com/originals/49/83/7d/49837d1615d806dee14301f191a1dc6a.jpg", "Vestido Sin Mangas Rosa Con Negro Alice+Olivia");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (450.0, 1, "S", "Algodón", "Pecho : 42 cm Cintura : 29 cm Largo: 82 cm", "Nuevo Zara Detalles: Ninguno", "https://i.pinimg.com/originals/9b/4b/cd/9b4bcd2ee54e9f8554651dea93a5d5b5.jpg", "Vestido Manga Larga Rosa Mexicano Zara");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (380.0, 1, "S", "nylon", "Pecho : 36 cm Cintura : 32 cm Largo: 78 cm", "Seminuevo Princess Polly Detalles: Ninguno", "https://www.pinterest.com.mx/pin/410601691044381998/", "Vestido Con Flores Marca Princess Polly");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (220.0, 1, "XS", "seda", "Pecho : 39 cm Cintura : 36 cm Largo: 94 cm", "Usado bb dakota Detalles: Ninguno", "https://i.pinimg.com/originals/ee/81/cb/ee81cbfe2acbe749a42079037cf6c0f8.jpg", "Vestido Sin Mangas Con Encaje Marca Bb Dakota");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (300.0, 2, "XS", "mezclilla", "Cintura: 39 cm Cadera : 44 cm Largo: 31 cm", "Seminuevo FOR ALL 7 MANKIND Detalles: Ninguno", "https://i.pinimg.com/originals/7c/b0/03/7cb00303b49429c987ad9ca9a94b2a62.jpg", "Short Blanco Marca For All 7 Mankind");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (200.0, 2, "S", "mezclilla", "Cintura: 41 cm Cadera : 49 cm Largo: 36 cm", "Seminuevo WILD FABLE Detalles: Ninguno", "https://i.pinimg.com/originals/d2/34/73/d23473e044277c74e80ee4a05d7580d1.jpg", "Short Tricolor Marca Wild Fable");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (300.0, 2, "M", "Algodón", "Cintura: 42 cm Cadera : 50 cm Largo: 36 cm", "Usado REFORMATION Detalles: Ninguno", "https://i.pinimg.com/originals/28/c2/52/28c252e2d56c759a05c7a25b7f6628b5.jpg", "Short Formal Beige Marca Reformation");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (260.0, 2, "XS", "Algodón", "Cintura: 39 cm Cadera : 44 cm Largo: 40 cm", "Seminuevo SUBDO Detalles: Ninguno", "https://i.pinimg.com/originals/da/f8/0a/daf80a75354748873a4a7147a0bb63b6.jpg", "Short Casual Rosa Marca Subdo");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (250.0, 2, "M", "mezclilla", "Cintura: 42 cm Cadera : 50 cm Largo: 36 cm", "Seminuevo Zara Detalles: Ninguno", "https://i.pinimg.com/originals/23/93/4b/23934b32fddc4a8759529548f73c46b1.jpg", "Short De Mezclilla Marza Zara");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (250.0, 2, "M", "Algodón", "Cintura: 41 cm Cadera : 48 cm Largo: 33 cm", "Seminuevo Madewell Detalles: Ninguno", "https://i.pinimg.com/originals/a1/2a/8b/a12a8bfe726928b569cc12d9146f6487.jpg", "Short Azul Y Blanco Marca Madewell");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (300.0, 3, "M", "mezclilla", "Cintura: 41 cm Cadera : 49 cm Largo: 39 cm", "Seminuevo Mother superior Detalles: Ninguno", "https://i.pinimg.com/originals/fb/a5/23/fba523c93da402d713f84b6a19c7813a.jpg", "Falda Animal Print Leopardo Marca Mother Superior");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (350.0, 3, "L", "lino", "Cintura: 41 cm Cadera : 49 cm Largo: 38 cm", "Nuevo Zara Detalles: Ninguno", "https://i.pinimg.com/originals/52/ff/b2/52ffb241f5a01ab70c7e46d5f9435ffa.jpg", "Falda Blanca Con Flores Marca Zara");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (260.0, 3, "L", "Algodón", "Cintura: 37 cm Cadera : 57 cm Largo: 40 cm", "Usado Pablo Detalles: Ninguno", "https://i.pinimg.com/originals/cd/54/5e/cd545e48962738937f31b557538b3327.jpg", "Falda De Flores Con Holanes Marca Pablo");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (300.0, 3, "M", "mezclilla", "Cintura: 42 cm Cadera : 49 cm Largo: 38 cm", "Usado R13 Detalles: Ninguno", "https://i.pinimg.com/originals/3a/62/df/3a62dfa1ae4cb2155f3632100a31465f.jpg", "Falda Verde Con Estampado De Leopardo Marca R13");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (300.0, 3, "S", "Algodón", "Cintura: 37 cm Cadera : 49 cm Largo: 45 cm", "Seminuevo TOPSHOP Detalles: Ninguno", "https://i.pinimg.com/originals/68/29/05/6829059c3cdbaef8be8468fb6c44ccec.jpg", "Falda Leopaedo Marca Topshop");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (300.0, 3, "S", "Poliester", "Cintura: 37 cm Cadera : 47 cm Largo: 42 cm", "Usado TOPSHOP Detalles: Ninguno", "https://i.pinimg.com/originals/1b/42/a9/1b42a9676594a6c564964d62d1a54efa.jpg", "Falda Negra Tipo Cuero Marca Topshop");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (350.0, 3, "M", "Poliester", "Cintura: 39 cm Cadera : 42 cm Largo: 40 cm", "Seminuevo INTERMIX Detalles: Ninguno", "https://i.pinimg.com/originals/a2/97/6a/a2976a3b1b0f6e07434872f8aec23df9.jpg", "Falda Negra Elegante Marca Intermix");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (150.0, 4, "M", "Poliester", "Pecho : 36 cm Cintura : 32 cm Largo: 46 cm", "Nuevo Zara Detalles: Ninguno", "https://i.pinimg.com/originals/4c/86/e3/4c86e3ee66b110c4037db01132daeb4f.jpg", "Blusa Azul  Marca Zara");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (350.0, 4, "L", "seda", "Pecho : 56 cm Cintura : 51 cm Largo: 59 cm", "Seminuevo JOIE Detalles: Ninguno", "https://www.pinterest.com.mx/pin/410601691044424783/", "Blusa Forma Casual Leopardo Marca Joie");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (250.0, 4, "XS", "Poliester", "Pecho : 38 cm Cintura : 33 cm Largo: 56 cm", "Usado GANNI Detalles: Ninguno", "https://i.pinimg.com/originals/1b/49/3f/1b493f4a11336826a7ee1ea019ad9a9a.jpg", "Blusa Leopardo Marca Ganni");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (200.0, 4, "XS", "Algodón", "Pecho : 38 cm Cintura : 33 cm Largo: 42cm", "Nuevo PRETTYLITTLETHING Detalles: Ninguno", "https://i.pinimg.com/originals/c2/2a/79/c22a792eb8a29030e4606ab9753b60cf.jpg", "Blusa Negra Espalda Descubierta Marca Prettylittlething");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (200.0, 4, "L", "Algodón", "Pecho : 51 cm Cintura : 52 cm Largo: 75 cm", "Seminuevo Brandy Melville Detalles: Ninguno", "https://i.pinimg.com/originals/01/e9/8e/01e98e396c0e5d91d6c2430a01b0aef1.jpg", "Blusa Larga Negra Marca Brandy Melville");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (150.0, 4, "M", "Algodón", "Pecho : 43 cm Cintura : 43 cm Largo: 31 cm", "Usado URBAN OUTFITTERS Detalles: Ninguno", "https://i.pinimg.com/originals/6e/6b/c9/6e6bc9e9ffe4bd8edd293b5ba67a14e8.jpg", "Blusa Croptop Marca Urban Outfitters");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (100.0, 4, "L", "Algodón", "Pecho : 46 cm Cintura : 46 cm Largo: 56 cm", "Usado jcrew Detalles: Ninguno", "https://i.pinimg.com/originals/67/76/8a/67768a3eddadcdddf3d529f364009ebe.jpg", "Blusa Con Estampado Marino Marca Jcrew");
INSERT INTO productos (precio, categoria_id_categorias, talla, material, medidas, descripcion, imagen, nombre) VALUES (100.0, 4, "L", "Algodón", "Pecho : 46 cm Cintura : 46 cm Largo: 56 cm", "Seminuevo jcrew Detalles: Ninguno", "https://i.pinimg.com/736x/08/54/57/0854571745550d1d12f0b237ff53f994.jpg", "Blusa  De Estrellas Marca Jcrew");


INSERT INTO pedidos (fecha_pedido, monto, cliente_id_clientes, correo, estado_pedido, direccion_envio, direccion_pedido) VALUES ('2024-04-04', 450.00, 1, "maria.garcia@gmail.com", "Pendiente", "Calle Principal 123, Ciudad", "Calle Principal 123, Ciudad");
INSERT INTO pedidos (fecha_pedido, monto, cliente_id_clientes, correo, estado_pedido, direccion_envio, direccion_pedido) VALUES ('2024-04-28', 380.00, 2, "luis.gonzalez@gmail.com", "Pendiente", "Av. Revolución 142, Monterrey", "Av. Revolución 142, Monterrey");
INSERT INTO pedidos (fecha_pedido, monto, cliente_id_clientes, correo, estado_pedido, direccion_envio, direccion_pedido) VALUES ('2024-04-27', 560.00, 3, "ximena.perez@gmail.com", "Pendiente", "Paseo de la Reforma 305, Ciudad de México", "Paseo de la Reforma 305, Ciudad de México");
INSERT INTO pedidos (fecha_pedido, monto, cliente_id_clientes, correo, estado_pedido, direccion_envio, direccion_pedido) VALUES ('2024-04-26', 600.00, 4, "michel.rodriguez@gmail.com", "Pendiente", "Calle Falsa 123, Cancún", "Calle Falsa 123, Cancún");
INSERT INTO pedidos (fecha_pedido, monto, cliente_id_clientes, correo, estado_pedido, direccion_envio, direccion_pedido) VALUES ('2024-04-25', 320.00, 5, "joel.mangel@gmail.com", "Pendiente", "Av. Siempre Viva 742, Springfield", "Av. Siempre Viva 742, Springfield");
INSERT INTO pedidos (fecha_pedido, monto, cliente_id_clientes, correo, estado_pedido, direccion_envio, direccion_pedido) VALUES ('2024-04-24', 450.00, 6, "ana.martinez@gmail.com", "Pendiente", "Blvd. Kukulcán Km 9, Zona Hotelera, Cancún", "Blvd. Kukulcán Km 9, Zona Hotelera, Cancún");
INSERT INTO pedidos (fecha_pedido, monto, cliente_id_clientes, correo, estado_pedido, direccion_envio, direccion_pedido) VALUES ('2024-04-23', 290.00, 7, "carlos.jimenez@gmail.com", "Pendiente", "Calle del Pez 47, Veracruz", "Calle del Pez 47, Veracruz");
INSERT INTO pedidos (fecha_pedido, monto, cliente_id_clientes, correo, estado_pedido, direccion_envio, direccion_pedido) VALUES ('2024-04-22', 410.00, 8, "isabel.vega@gmail.com", "Pendiente", "Av. Universidad 1000, Ciudad Universitaria, Ciudad de México", "Av. Universidad 1000, Ciudad Universitaria, Ciudad de México");
INSERT INTO pedidos (fecha_pedido, monto, cliente_id_clientes, correo, estado_pedido, direccion_envio, direccion_pedido) VALUES ('2024-04-21', 500.00, 9, "raul.dominguez@gmail.com", "Pendiente", "Calle Nueva 456, Mérida", "Calle Nueva 456, Mérida");
INSERT INTO pedidos (fecha_pedido, monto, cliente_id_clientes, correo, estado_pedido, direccion_envio, direccion_pedido) VALUES ('2024-04-20', 350.00, 10, "elena.nieto@gmail.com", "Pendiente", "Calle Vieja 321, Guanajuato", "Calle Vieja 321, Guanajuato");